In [1]:
import pandas as pd
import scipy.stats as stats

In [5]:
df = pd.read_csv('COVID-19 SSR.csv')

In [6]:
df.head()

,Unnamed: 0,ID,Region of residence,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,0,R1,Delhi-NCR,21,2.0,GOOD,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4,Increased,NO,Cooking,YES,YES,School/college
1,1,R2,Delhi-NCR,21,0.0,EXCELLENT,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,2,R3,Delhi-NCR,20,7.0,VERY POOR,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,3,R4,Delhi-NCR,20,3.0,VERY POOR,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,4,R5,Delhi-NCR,21,3.0,GOOD,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4,Remain Constant,NO,Social Media,NO,NO,Travelling

In [13]:
df.describe()

,Unnamed: 0,Age of Subject,Time spent on Online Class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Number of meals per day
count,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000
mean,590.500000,20.165821,3.208841,2.911591,0.765821,7.871235,2.365694,2.917936
std,341.358316,5.516467,2.101756,2.140590,0.724451,1.615762,1.767336,0.828698
min,0.000000,7.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000
25%,295.250000,17.000000,2.000000,2.000000,0.000000,7.000000,1.000000,2.000000
50%,590.500000,20.000000,3.000000,2.000000,1.000000,8.000000,2.000000,3.000000
75%,885.750000,21.000000,5.000000,4.000000,1.000000,9.000000,3.000000,3.000000
max,1181.000000,59.000000,10.000000,18.000000,5.000000,15.000000,10.000000,8.000000

In [18]:
print(df.dtypes.describe()['top'])

object

In [35]:
df['Rating of Online Class experience'] = df['Rating of Online Class experience'].str.title()

In [40]:
print(df['Rating of Online Class experience'].head())

0         Good
1    Excellent
2    Very Poor
3    Very Poor
4         Good
Name: Rating of Online Class experience, dtype: object

In [26]:
txt.title()

'Hello'

In [2]:
df = pd.read_csv('COVID-19 Survey Student Responses.csv')

In [3]:
df.head()

,ID,Region of residence,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,R1,Delhi-NCR,21,2.0,Good,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4,Increased,NO,Cooking,YES,YES,School/college
1,R2,Delhi-NCR,21,0.0,Excellent,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,R3,Delhi-NCR,20,7.0,Very poor,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,R4,Delhi-NCR,20,3.0,Very poor,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,R5,Delhi-NCR,21,3.0,Good,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4,Remain Constant,NO,Social Media,NO,NO,Travelling

In [10]:
df = df.assign(sleep_normal=['yes' if i>=7 and i<=8 else 'no' for i in df['Time spent on sleep']])

In [11]:
df.head()

,ID,Region of residence,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most,sleep_normal
0,R1,Delhi-NCR,21,2.0,Good,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4,Increased,NO,Cooking,YES,YES,School/college,yes
1,R2,Delhi-NCR,21,0.0,Excellent,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely,no
2,R3,Delhi-NCR,20,7.0,Very poor,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3,Remain Constant,NO,Listening to music,NO,YES,Travelling,no
3,R4,Delhi-NCR,20,3.0,Very poor,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3,Decreased,NO,Watching web series,NO,NO,"Friends , relatives",no
4,R5,Delhi-NCR,21,3.0,Good,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4,Remain Constant,NO,Social Media,NO,NO,Travelling,yes

In [25]:
print(df.loc[df['sleep_normal'] == 'no', 'sleep_normal'].count())

531

In [36]:
df['Time spent on TV'] = df['Time spent on TV'].replace(['n','N','No tv',' '], 0)

In [45]:
print(df['Time spent on TV'].dtypes)

object

In [46]:
df = df.assign(sleep_normal_cat=['normal' if i>7 else 'not normal' for i in df['Time spent on sleep']])

In [47]:
df = df.assign(media_normal_cat=['normal' if i<2 else 'not normal' for i in df['Time spent on social media']])

In [66]:
cross = pd.crosstab(df.sleep_normal_cat, df.media_normal_cat)
cross.iloc[1,1]

280

In [67]:
print(stats.chisquare([cross.iloc[0,0], cross.iloc[0,1], cross.iloc[1,0], cross.iloc[1,1]]).pvalue)

7.839886225377429e-29

In [69]:
df['Health issue during lockdown'] = df['Health issue during lockdown'].replace({'YES':1,'NO':0})

In [75]:
df['Health issue during lockdown'].nunique()

2

In [89]:
tbl = df['Stress busters'].str.contains('book', regex=False).value_counts()

In [97]:
print(tbl.iloc[1])

85

In [104]:
top_media = df['Prefered social media platform'].describe()['top']

In [115]:
mean_time = df.loc[df['Prefered social media platform'] == top_media, 'Time spent on social media'].mean()

In [116]:
print(round(mean_time, 2))

2.91

In [54]:
media_time = round(df[['Prefered social media platform', 'Time spent on social media']].groupby(by='Prefered social media platform').mean().sort_values('Time spent on social media', ascending=False),2)

In [57]:
print(media_time['Time spent on social media'].idxmax(), media_time['Time spent on social media'].max())

Talklife 10.0